CREATE DATABASE IF NOT EXISTS `sea` CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `sea`;

CREATE TABLE  `sea`.`links` (
`link_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`link` VARCHAR( 500 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`link_text` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`priority` INT NOT NULL DEFAULT  '0'
) ENGINE = MYISAM ;

CREATE TABLE  `sea`.`pages` (
`page_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`content` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`title` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE = MYISAM ;

